baseURL = "/"
title = "GitHub Style"
#googleAnalytics = "UA-123-456-789"
theme = "github-style"
copyright = "© 2019."

[params]
  author = "Paul Rapuluchukwu"
  description = "Backend developer"
  github = "rapulu"
  #facebook = "example"
  twitter = "isRapulu"
  #misskey = "user profile url"
  #mastodon = "user profile url"
  email = "rapulu@yahoo.com"
  #utterances = "example/example.github.io"
  avatar = "/images/rapulu.jpg"
  url = "https://rapulu.xyz"